def get_product():
    return {
        'brandId': 2035,
        'brandName': 'New Face',
        'brandSummary': 'New Face',
        'brandLogoImage': 'https://s3.amazonaws.com/Glambox.Catalog.Brand/Logo_2035_SML.png',
        'productName': 'Máscara Facial Hidratação e Nutrição ',
        'activeFeedbackId': 0,
        'defaultProductVariantId': 81695,
        'productSummary': 'Máscara Facial Hidratação e Nutrição',
        'descriptionArticleId': 8775,
        'productVariantId': 81695,
        'productId': 6961,
        'productVariantName': 'Máscara Facial Hidratação e Nutrição 20g',
        'variantSummary': 'Máscara Facial Hidratação e Nutrição 20g',
        'weight': 25.0,
        'salePrice': 0.0,
        'saleStock': 0,
        'tradePoints': 80.0,
        'tradeStock': 0,
        'maxTradesPerPerson': 1,
        'tradeActive': True,
        'defaultImageURL': 'https://s3.amazonaws.com/Glambox.Catalog.ProductVariant/ProductVariantImage_81695_SML.jpg',
        'externalStoreUrl': None,
        'orderCount': 0,
        'dateCreated': 1614087592000,
        'dateUpdated': 1620748165000,
        'tradeCount': 0,
        'ratingAverage': 0.0,
        'reviewCount': 0,
        'articleTitle': 'New Face - Máscara Facial Hidratação e Nutrição',
        'articleTags': '',
        'stockCount': 57,
        'displayOrder': 226,
        'tradeable': True,
        'showOnWebsite': True,
        'sellable': False
    }

print(__name__)
